//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDTDomainModel.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationEnumsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationEnumsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDTDomainModel.Enums.Resources.ApplicationEnumsResources", typeof(ApplicationEnumsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elbow.
        /// </summary>
        internal static string Elbow {
            get {
                return ResourceManager.GetString("Elbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush Nozzle.
        /// </summary>
        internal static string FlushNozzle {
            get {
                return ResourceManager.GetString("FlushNozzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Pipe.
        /// </summary>
        internal static string HalfPipe {
            get {
                return ResourceManager.GetString("HalfPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Separetor.
        /// </summary>
        internal static string HorizontalSeparator {
            get {
                return ResourceManager.GetString("HorizontalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet Cyclones.
        /// </summary>
        internal static string InletCyclones {
            get {
                return ResourceManager.GetString("InletCyclones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet Vane Diffuser.
        /// </summary>
        internal static string InletVaneDiffuser {
            get {
                return ResourceManager.GetString("InletVaneDiffuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ishii and Kataoka.
        /// </summary>
        internal static string IshiiKataoka {
            get {
                return ResourceManager.GetString("IshiiKataoka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        internal static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slotted Pipe.
        /// </summary>
        internal static string SlottedPipe {
            get {
                return ResourceManager.GetString("SlottedPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splash Plate.
        /// </summary>
        internal static string SplashPlate {
            get {
                return ResourceManager.GetString("SplashPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatterson, Dallman and Hanratty.
        /// </summary>
        internal static string TattersonDallmanHanratty {
            get {
                return ResourceManager.GetString("TattersonDallmanHanratty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US.
        /// </summary>
        internal static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-Baffle.
        /// </summary>
        internal static string VBaffle {
            get {
                return ResourceManager.GetString("VBaffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Separator.
        /// </summary>
        internal static string VerticalSeparator {
            get {
                return ResourceManager.GetString("VerticalSeparator", resourceCulture);
            }
        }
    }
}
