//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDTDomainModel.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MeasurementUnitsEnumResouces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeasurementUnitsEnumResouces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDTDomainModel.Enums.Resources.MeasurementUnitsEnumResouces", typeof(MeasurementUnitsEnumResouces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar.
        /// </summary>
        public static string bar {
            get {
                return ResourceManager.GetString("bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ºC.
        /// </summary>
        public static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string Centimeter {
            get {
                return ResourceManager.GetString("Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cP.
        /// </summary>
        public static string Centipoise {
            get {
                return ResourceManager.GetString("Centipoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft³/s.
        /// </summary>
        public static string CubicFeetPerSecond {
            get {
                return ResourceManager.GetString("CubicFeetPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m³/h.
        /// </summary>
        public static string CubicMeterPerHour {
            get {
                return ResourceManager.GetString("CubicMeterPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m³/s.
        /// </summary>
        public static string CubicMeterPerSecond {
            get {
                return ResourceManager.GetString("CubicMeterPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dyn/cm.
        /// </summary>
        public static string DynePerCentimeter {
            get {
                return ResourceManager.GetString("DynePerCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ºF.
        /// </summary>
        public static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        public static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft/s.
        /// </summary>
        public static string FeetPerSecond {
            get {
                return ResourceManager.GetString("FeetPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpm.
        /// </summary>
        public static string GallonPerMinute {
            get {
                return ResourceManager.GetString("GallonPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string Gram {
            get {
                return ResourceManager.GetString("Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g/cm³.
        /// </summary>
        public static string GramPerCubicCentimeter {
            get {
                return ResourceManager.GetString("GramPerCubicCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g/gmol.
        /// </summary>
        public static string GramPerGramMol {
            get {
                return ResourceManager.GetString("GramPerGramMol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string Kilogram {
            get {
                return ResourceManager.GetString("Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg/m³.
        /// </summary>
        public static string KilogramPerCubicMeter {
            get {
                return ResourceManager.GetString("KilogramPerCubicMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg/h.
        /// </summary>
        public static string KilogramPerHour {
            get {
                return ResourceManager.GetString("KilogramPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg/kgmol.
        /// </summary>
        public static string KilogramPerKilogramMol {
            get {
                return ResourceManager.GetString("KilogramPerKilogramMol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg/m.s.
        /// </summary>
        public static string KilogramPerMetersecond {
            get {
                return ResourceManager.GetString("KilogramPerMetersecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg/m.s².
        /// </summary>
        public static string KilogramPerMeterSquaredSecond {
            get {
                return ResourceManager.GetString("KilogramPerMeterSquaredSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg/s.
        /// </summary>
        public static string KilogramPerSecond {
            get {
                return ResourceManager.GetString("KilogramPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string Kilometer {
            get {
                return ResourceManager.GetString("Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string MeterPerSecond {
            get {
                return ResourceManager.GetString("MeterPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to µm.
        /// </summary>
        public static string Micrometer {
            get {
                return ResourceManager.GetString("Micrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        public static string Miligram {
            get {
                return ResourceManager.GetString("Miligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string Milimeter {
            get {
                return ResourceManager.GetString("Milimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/m.
        /// </summary>
        public static string NewtonPerMeter {
            get {
                return ResourceManager.GetString("NewtonPerMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oz.
        /// </summary>
        public static string Ounce {
            get {
                return ResourceManager.GetString("Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa.
        /// </summary>
        public static string Pascal {
            get {
                return ResourceManager.GetString("Pascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa.s.
        /// </summary>
        public static string PascalSecond {
            get {
                return ResourceManager.GetString("PascalSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        public static string Pound {
            get {
                return ResourceManager.GetString("Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb/ft³.
        /// </summary>
        public static string PoundPerCubicFeet {
            get {
                return ResourceManager.GetString("PoundPerCubicFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb/ft.s.
        /// </summary>
        public static string PoundPerFeetSecond {
            get {
                return ResourceManager.GetString("PoundPerFeetSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb/ft.s².
        /// </summary>
        public static string PoundPerFeetSquaredSecond {
            get {
                return ResourceManager.GetString("PoundPerFeetSquaredSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb/h.
        /// </summary>
        public static string PoundPerHour {
            get {
                return ResourceManager.GetString("PoundPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb/lbmol.
        /// </summary>
        public static string PoundPerPoundMol {
            get {
                return ResourceManager.GetString("PoundPerPoundMol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb/s.
        /// </summary>
        public static string PoundPerSecond {
            get {
                return ResourceManager.GetString("PoundPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psi.
        /// </summary>
        public static string PoundPerSquareInch {
            get {
                return ResourceManager.GetString("PoundPerSquareInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yrd.
        /// </summary>
        public static string Yards {
            get {
                return ResourceManager.GetString("Yards", resourceCulture);
            }
        }
    }
}
